package cmd

import (
	"fmt"
	"net/url"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

type CreateDBConfig struct {
	DBName       string
	Owner        string
	Password     string
	NoSchemaSQL  bool
	DropExisting bool
}

func buildCreateDBSQL(cfg CreateDBConfig) string {
	owner := quoteIdent(cfg.Owner)
	dbName := quoteIdent(cfg.DBName)
	password := quoteString(cfg.Password)

	var b strings.Builder

	b.WriteString("-- Generated by nnry-text-util createdb\n\n")

	if cfg.DropExisting {
		b.WriteString(fmt.Sprintf("-- Drop database if exists\n"))

		// Terminate connections first, then drop
		b.WriteString(fmt.Sprintf("SELECT pg_terminate_backend(pg_stat_activity.pid)\n"))
		b.WriteString(fmt.Sprintf("FROM pg_stat_activity\n"))
		b.WriteString(fmt.Sprintf("WHERE pg_stat_activity.datname = %s AND pid <> pg_backend_pid();\n\n", quoteString(cfg.DBName)))
		b.WriteString(fmt.Sprintf("DROP DATABASE IF EXISTS %s;\n\n", dbName))
		b.WriteString(fmt.Sprintf("DROP ROLE IF EXISTS %s;\n\n", owner))
	}

	b.WriteString(fmt.Sprintf("-- Create the user (role)\n"))
	b.WriteString(fmt.Sprintf("CREATE ROLE %s WITH LOGIN PASSWORD %s;\n\n", owner, password))

	b.WriteString(fmt.Sprintf("-- Create the database\n"))
	b.WriteString(fmt.Sprintf("CREATE DATABASE %s;\n\n", dbName))

	b.WriteString(fmt.Sprintf("-- Grant database-level privileges\n"))
	b.WriteString(fmt.Sprintf("GRANT ALL PRIVILEGES ON DATABASE %s TO %s;\n\n", dbName, owner))

	if !cfg.NoSchemaSQL {
		b.WriteString(fmt.Sprintf("-- Connect to the database to grant schema privileges\n"))
		b.WriteString(fmt.Sprintf("\\c %s\n\n", cfg.DBName))

		b.WriteString(fmt.Sprintf("-- Grant schema privileges\n"))
		b.WriteString(fmt.Sprintf("GRANT ALL ON SCHEMA public TO %s;\n", owner))
		b.WriteString(fmt.Sprintf("GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO %s;\n", owner))
		b.WriteString(fmt.Sprintf("GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO %s;\n", owner))
		b.WriteString(fmt.Sprintf("GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO %s;\n\n", owner))

		b.WriteString(fmt.Sprintf("-- Set default privileges for future objects\n"))
		b.WriteString(fmt.Sprintf("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO %s;\n", owner))
		b.WriteString(fmt.Sprintf("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO %s;\n", owner))
		b.WriteString(fmt.Sprintf("ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO %s;\n", owner))

		b.WriteString(fmt.Sprintf("\n-- Revoke default public schema permissions for extra safety\n"))
		b.WriteString(fmt.Sprintf("REVOKE ALL ON SCHEMA public FROM PUBLIC;\n"))
		b.WriteString(fmt.Sprintf("GRANT ALL ON SCHEMA public TO %s;\n", owner))
		b.WriteString(fmt.Sprintf("GRANT USAGE ON SCHEMA public TO PUBLIC;\n"))
	}

	return b.String()
}

func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

func quoteString(s string) string {
	return `'` + strings.ReplaceAll(s, `'`, `''`) + `'`
}

var createdbCmd = &cobra.Command{
	Use:   "createdb",
	Short: "Generate SQL script to create a database with its owner",
	Long: `Generate a PostgreSQL SQL script that creates a database, a user (owner),
and grants full privileges to that user.

The script is printed to stdout and can be pasted or \\i'd inside a psql session.
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		dbName, _ := cmd.Flags().GetString("db-name")
		owner, _ := cmd.Flags().GetString("owner")
		password, _ := cmd.Flags().GetString("password")
		noSchema, _ := cmd.Flags().GetBool("no-schema-sql")
		drop, _ := cmd.Flags().GetBool("drop-existing")

		if dbName == "" {
			return fmt.Errorf("--db-name is required")
		}
		if owner == "" {
			return fmt.Errorf("--owner is required")
		}

		if password == "" {
			charset := BuildCharset(SecretOptions{Alphanumeric: true})
			generated, err := generateSecret(24, charset)
			if err != nil {
				return fmt.Errorf("generating password: %w", err)
			}
			password = generated
			fmt.Fprintf(os.Stderr, "Generated password: %s\n", password)
		}

		connURL := &url.URL{
			Scheme: "postgresql",
			User:   url.UserPassword(owner, password),
			Host:   "localhost:5432",
			Path:   dbName,
		}
		fmt.Fprintf(os.Stderr, "Connection URL: %s\n", connURL.String())

		cfg := CreateDBConfig{
			DBName:       dbName,
			Owner:        owner,
			Password:     password,
			NoSchemaSQL:  noSchema,
			DropExisting: drop,
		}

		sql := buildCreateDBSQL(cfg)
		fmt.Println(sql)
		return nil
	},
}

func init() {
	createdbCmd.Flags().StringP("db-name", "n", "", "Database name (required)")
	createdbCmd.Flags().StringP("owner", "o", "", "Database owner username (required)")
	createdbCmd.Flags().StringP("password", "p", "", "Owner password (required)")
	createdbCmd.Flags().Bool("no-schema-sql", false, "Skip schema-level GRANT and ALTER DEFAULT statements")
	createdbCmd.Flags().Bool("drop-existing", false, "Add DROP DATABASE/ROLE IF EXISTS statements at the start")

	rootCmd.AddCommand(createdbCmd)
}